# For Elasticsearch to store its indexes, we usually need to increase the host machine's mmap count: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
# If `sysctl vm.max_map_count` is < 262144, then `sysctl -w vm.max_map_count=262144` and set vm.max_map_count in /etc/sysctl.conf to the same value # elasticsearch(lx) had 16777215
version: '2'
services:
  phy-elasticsearch-live:
    # container configuration https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    container_name: phy-elasticsearch-live
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - "cluster.name=isaac-phy-content"
      - "network.host=${LOCAL_PHY_ELASTICSEARCH_IP}"
      - "discovery.seed_hosts=${REMOTE_PHY_ELASTICSEARCH_IP},${LOCAL_PHY_ELASTICSEARCH_VOTER_IP},${REMOTE_PHY_ELASTICSEARCH_VOTER_IP}" # other master-eligible nodes
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - "bootstrap.memory_lock=true" # part of disabling swap
      - "node.name=${HOSTNAME}-phy-node"
      # ! When starting a brand new Elasticsearch cluster for the first time, un-comment for cluster bootstrap VV
      # - "cluster.initial_master_nodes=${HOSTNAME}-phy-node"
      - "http.max_content_length=512mb"
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${PHY_ELASTIC_PASSWORD}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.client_authentication=required
      - xpack.security.transport.ssl.keystore.path=certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=certs/elastic-certificates.p12
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock: -1 # part of disabling swap
      nproc: -1 # doc suggestion: at least 4,096 our docker default is unlimited
      nofile: 1048576 # doc suggestion: at least 65,536
    volumes:
      - phy-elasticsearch-content:/usr/share/elasticsearch/data
      - /local/data/elasticsearch/certificates:/usr/share/elasticsearch/config/certs
    networks:
      default:
        ipv4_address: "${LOCAL_PHY_ELASTICSEARCH_IP}"
    restart: unless-stopped

  phy-elasticsearch-voter-live:
    # container configuration https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    container_name: phy-elasticsearch-voter-live
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - "cluster.name=isaac-phy-content"
      - "network.host=${LOCAL_PHY_ELASTICSEARCH_VOTER_IP}"
      - "discovery.seed_hosts=${LOCAL_PHY_ELASTICSEARCH_IP},${REMOTE_PHY_ELASTICSEARCH_IP},${REMOTE_PHY_ELASTICSEARCH_VOTER_IP}" # other master-eligible nodes
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true" # part of disabling swap
      - "node.name=${HOSTNAME}-phy-voter-node"
      - "node.roles=master,voting_only"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${PHY_ELASTIC_PASSWORD}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.client_authentication=required
      - xpack.security.transport.ssl.keystore.path=certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=certs/elastic-certificates.p12
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock: -1 # part of disabling swap
      nproc: 4096 # doc suggestion: at least 4,096
      nofile: 65536 # doc suggestion: at least 65,536
    volumes:
      - /local/data/elasticsearch/certificates:/usr/share/elasticsearch/config/certs
    networks:
      default:
        ipv4_address: "${LOCAL_PHY_ELASTICSEARCH_VOTER_IP}"
    restart: unless-stopped

  cs-elasticsearch-live:
    # container configuration https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    container_name: cs-elasticsearch-live
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - "cluster.name=isaac-cs-content"
      - "network.host=${LOCAL_CS_ELASTICSEARCH_IP}"
      - "discovery.seed_hosts=${REMOTE_CS_ELASTICSEARCH_IP},${LOCAL_CS_ELASTICSEARCH_VOTER_IP},${REMOTE_CS_ELASTICSEARCH_VOTER_IP}" # other master-eligible nodes
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - "bootstrap.memory_lock=true" # part of disabling swap
      - "node.name=${HOSTNAME}-cs-node"
      # ! When starting a brand new Elasticsearch cluster for the first time, un-comment for cluster bootstrap VV
      # - "cluster.initial_master_nodes=${HOSTNAME}-cs-node"
      - "http.max_content_length=512mb"
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${PHY_ELASTIC_PASSWORD}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.client_authentication=required
      - xpack.security.transport.ssl.keystore.path=certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=certs/elastic-certificates.p12
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock: -1 # part of disabling swap
      nproc: -1 # doc suggestion: at least 4,096 our docker default is unlimited
      nofile: 1048576 # doc suggestion: at least 65,536
    volumes:
      - cs-elasticsearch-content:/usr/share/elasticsearch/data
      - /local/data/elasticsearch/certificates:/usr/share/elasticsearch/config/certs
    networks:
      default:
        ipv4_address: "${LOCAL_CS_ELASTICSEARCH_IP}"
    restart: unless-stopped

  cs-elasticsearch-voter-live:
    # container configuration https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    container_name: cs-elasticsearch-voter-live
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - "cluster.name=isaac-cs-content"
      - "network.host=${LOCAL_CS_ELASTICSEARCH_VOTER_IP}"
      - "discovery.seed_hosts=${LOCAL_CS_ELASTICSEARCH_IP},${REMOTE_CS_ELASTICSEARCH_IP},${REMOTE_CS_ELASTICSEARCH_VOTER_IP}" # other master-eligible nodes
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true" # part of disabling swap
      - "node.name=${HOSTNAME}-cs-voter-node"
      - "node.roles=master,voting_only"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${PHY_ELASTIC_PASSWORD}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.client_authentication=required
      - xpack.security.transport.ssl.keystore.path=certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=certs/elastic-certificates.p12
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock: -1 # part of disabling swap
      nproc: 4096 # doc suggestion: at least 4,096
      nofile: 65536 # doc suggestion: at least 65,536
    volumes:
      - /local/data/elasticsearch/certificates:/usr/share/elasticsearch/config/certs
    networks:
      default:
        ipv4_address: "${LOCAL_CS_ELASTICSEARCH_VOTER_IP}"
    restart: unless-stopped

volumes:
  phy-elasticsearch-content:
    external:
      name: phy-elasticsearch-content
  cs-elasticsearch-content:
    external:
      name: cs-elasticsearch-content

networks:
  default:
    external:
      name: isaac
